### ISSUE TITLE
De-CLAW the lobster

### ISSUE THREAD

**Issue by whikloj** [Islandora/documentation#1082]
This is a follow-on from #1020 

The task is to go through the code base and try to remove references to the CLAW project name and replace them (where appropriate) with "Islandora 8"

**Comment by jonathangreen** [comment]
I don't want to expand the scope of this one too much, so maybe this deserves its own ticket, but how are we going to manage the repositories moving forward with Islandora v8 since everything is in the CLAW organization. Whatever we do it will probably be painful, but perhaps it's best to rip that bandaid off before 1.0?

**Comment by jonathangreen** [comment]
When 1.0 comes out it seems like something for Islandora v8 should live in the [`Islandora`](https://github.com/islandora) organization even if it's just a repo (or maybe a branch on [`Islandora/Islandora`](https://github.com/islandora/islandora) 🤷‍♂️) called Islandora8 that points out to a different organization. 

Taking a long term view, at some point Islandora v8 is going to become what people think of as Islandora and at that point having [`Islandora/Islandora`](https://github.com/islandora/islandora) point to v7 maybe a bit confusing. 

Looking at some projects we are closely aligned with and how they manage this: 

### Drupal
https://github.com/drupal/drupal
https://www.drupal.org/project/drupal

For Drupal they keep everything in the same repo with different branches. This is doable for us, but we would need to squash together two repos without the same root, but git supports that. (In fact 6.x and 7.x probably don't have the same root commit either).

### Fedora
It looks like Fedora renamed its old organization to [`fcrepo3`](https://github.com/fcrepo3) and created a new [`fcrepo4`](https://github.com/fcrepo4) organization. 

This is probably the easiest thing we could do... but it could cause a lot of breakage in links pointing to the current [`Islandora/Islandora`](https://github.com/islandora/islandora) repo. It could probably be accomplished with some messaging and warning to the community though. 

I would like to see us avoid the pitfalls of throwing a version into the organization name like [`fcrepo4`](https://github.com/fcrepo4), since Islandora 9 isn't going to be that far behind Islandora 8.

**Comment by DonRichards** [comment]
+1 for keeping/moving it in islandora with branches like 8.x. 
This would make it much easier for people to see it's this as the next version and not a completely different product.

**Comment by manez** [comment]
@whikloj can we close this (as old and all merged) and open up a new one to track lingering CLAWs, like the ones turning up in the master/main rename?

**Comment by manez** [comment]
Fresh issue for tracking: https://github.com/Islandora/documentation/issues/1600
