### ISSUE TITLE
Add re-ordering support to our existing 'Members' admin view

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1262]
If you go to the 'Members' tab for an object, you get an admin view with all of the members belonging to an object.  According to [this issue for the weight module](https://www.drupal.org/project/weight/issues/2844791), you can configure the view to become a drag 'n drop interface for re-ordering children.  Add this to our view so we can re-order pages.

**Comment by dannylamb** [comment]
Depends on https://github.com/Islandora-CLAW/CLAW/issues/1261

**Comment by dannylamb** [comment]
Linking to https://github.com/Islandora-CLAW/CLAW/issues/932

**Comment by seth-shaw-unlv** [comment]
We have a complication. Our new weight_field uses the 'integer' field type instead of the weight module's 'weight' field type. This is good in that we can force it to conform to the semantic requirements of `http:purl.org/co/index` but this blocks us from using the weight module's drag-n-drop functionality.

Two possible resolutions:

1. Change the field_weight to use the weight field type. **Pros**: we get to use drag-n-drop. **Con**: it doesn't fit the semantics of `http://purl.org/co/index`; however, we can alleviate this by using `https://schema.org/position` instead which would take any integer value.
1. Port the weight module's drag-n-drop to use integers with our configured min/max settings. **Pro**: we get to use drag-n-drop and keep our integer-based field. **Con**: more code we have to support ourselves.

Between the two, I would prefer the former over the latter.

**Comment by dannylamb** [comment]
I'd make it a weight field. I always opt for the least code solution.

**Comment by seth-shaw-unlv** [comment]
We have three UI options for creating a re-order page:

- We can add it to the existing Members Tab so that you would have a top area for bulk actions and a bottom area for re-ordering (we can create a label for it, it just isn't shown here):
<img width="677" alt="Screen Shot 2019-09-10 at 2 49 33 PM" src="https://user-images.githubusercontent.com/29869988/64653129-81788000-d3da-11e9-9fef-c8af98310683.png">
- We can just create a link on the members tab to the re-order page (but then the re-order page has a significant jump in interface as you loose the tabs):
<img width="424" alt="Screen Shot 2019-09-10 at 2 49 52 PM" src="https://user-images.githubusercontent.com/29869988/64653203-ac62d400-d3da-11e9-8234-4dbfefdba4ab.png">
- We could make another tab, although getting it to show up for a screen-shot is eluding me.

**Comment by seth-shaw-unlv** [comment]
So I think this is our best option:
<img width="960" alt="Screen Shot 2019-09-10 at 3 19 55 PM" src="https://user-images.githubusercontent.com/29869988/64654556-77f11700-d3de-11e9-835d-69c39c478481.png">

HOWEVER, it adds a dependency on islandora_defaults because that is where field_weight is defined. 🙄 So, it looks like I will need to create this as a separate view in islandora_defaults. The question then is how to join them together again. Some funky config edits on the install hook?

**Comment by seth-shaw-unlv** [comment]
I've updated the PR to just create another tab. It makes the PR much cleaner.

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora-CLAW/islandora/commit/d45f94801739aa7b0bf22796084a93ffd5ed0b36
