### ISSUE TITLE
Openseadragon view mode sets the viewer to a small fixed width

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1328]
![image](https://user-images.githubusercontent.com/20773151/68702349-0b6dd200-055f-11ea-8523-5fe588a8fe8a.png)

This is for just when using the Openseadragon view mode for a single image or page, not a full paged content object.

**Comment by mjordan** [comment]
Just confirming this behavior. Running carapace at commit 515b9194641a1798c549ce8eb9253b7713fca86d.

![carapice](https://user-images.githubusercontent.com/403918/68828395-5fa9ac80-065a-11ea-9aa6-0df839fb216d.png)

**Comment by dflitner** [comment]
.node .field-type-image__item is set to inline_block. Removing this makes the viewer go full screen width. Is that the desired behavior?
<img width="1067" alt="Screen Shot 2019-11-15 at 1 18 10 PM" src="https://user-images.githubusercontent.com/6807228/68973031-73fcbf00-07aa-11ea-948a-2b6e6e944847.png">

At any rate, that rule is set in node.css and rather than remove it and perhaps upset other images that are supposed to be inline-block, we can do:
.field-formatter-openseadragon-image .field-type-image__item {
    display: initial;
}
to override it for Open Seadragon.

**Comment by dannylamb** [comment]
@dflitner can haz PR?

**Comment by dflitner** [comment]
Sorry thought I had already made this a PR. It was sitting on my local machine.

**Comment by dflitner** [comment]
Per Seth's suggestion, I'm looking at changing the CSS in Open Seadragon instead of Carapace. However I'm not sure what the desired behavior actually is. We have a manual height set of 640px because otherwise OSD shrinks down to tiny for some reason. It's supposed to match the size of the containing element, which is why changing .field-type-image__item was working. (P.S. adding width:100% to this also works instead of changing the display)

With the previous change and anything else I try to make the thing display bigger, it actually stretches out the image that it's displaying. Is it supposed to show the original image at its original size or is it meant to display at a certain size even if it's pixelly?

In my opinion, the ideal display behavior would be to display the image at its original size up to the width of the content area.

Perhaps I'm only noticing this because I'm using ancient internet memes as sample images.

Image with no viewer:
Image is 420x290px
<img width="479" alt="Screen Shot 2020-02-04 at 3 04 18 PM" src="https://user-images.githubusercontent.com/6807228/73791523-b9a0a680-475f-11ea-8a31-f05e311b3bb3.png">

Image with OSD at full width:
Hard to see in the screenshot but it's got visual artifacts.
<img width="994" alt="Screen Shot 2020-02-04 at 3 04 48 PM" src="https://user-images.githubusercontent.com/6807228/73791517-b60d1f80-475f-11ea-81fb-a5569419bc6f.png">

I'm still poking at this but it's being annoying.

**Comment by seth-shaw-unlv** [comment]
Resolved with https://github.com/Islandora/openseadragon/commit/ad2d2d1691a2c1c05b0bb56185faf699b8d563ed. Thanks @dflitner!
