### ISSUE TITLE
islandora_breadcrumbs seems to not include Home

### ISSUE THREAD

**Issue by wgilling** [Islandora/documentation#1430]
If the current theme is configured to not always hide the "Home" in breadcrumbs, I would expect that this module would include the site Home link as well.

Is this due to the initialization of $breadcrumbs in the build() function as 
`  $breadcrumbs = new Breadcrumb();`

instead of something like this:
`    $breadcrumbs = parent::build($route_match);`

**Comment by seth-shaw-unlv** [comment]
Thanks for reporting this @wgilling.

**Comment by seth-shaw-unlv** [comment]
I looked at this a bit more, and I don't think `parent::build($route_match)` will work because we are implementing an interface, not extending a base class.

All of the examples of custom breadcrumbs I've found use the `$breadcrumbs = new Breadcrumb();` convention but also add `$breadcrumb->addLink(Link::createFromRoute($this->t('Home'), '<front>'));` right after it; which will do what you suggest. Although, I'm inclined to make it configurable so we can turn it off if we want.

**Comment by wgilling** [comment]
I am not entirely sure that you need to have a separate configuration for suppressing the Home in the breadcrumb.  The theme should take care of removing the Home breadcrumb (as in at_core and other theme code does in the preprocess_breadcrumb function based on the $config['breadcrumb_home'] being checked.

**Comment by seth-shaw-unlv** [comment]
I'll run with that. 👍

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/islandora/commit/f5d98ab709b90327eae18898cc512dfc5fa9a798
