### ISSUE TITLE
Houdini/README.md out-of-date?

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1493]
Houdini/README.md refers to config.yaml in `Houdini/cfg/config.example.yaml` but I think this is out-of-date as there is also config in `Houdini/config/services.yaml` and similar files...

**Comment by whikloj** [comment]
Oooo yeah, that's on me. I'll try to update the documentation tomorrow.

**Comment by kayakr** [comment]
@whikloj Thanks in advance for that. If you don't mind, where do I change logging destination (currently going to `Houdini/var/log/dev.log`)?

**Comment by whikloj** [comment]
Ok, this depends on your environment which is somethingi need to document.

But I'd try here first.

https://github.com/Islandora/Crayfish/blob/dev/Houdini/config/packages/dev/monolog.yaml#L5

**Comment by kayakr** [comment]
@whikloj Cheers, will try it...

**Comment by joshdentremont** [comment]
@whikloj We've been following the manual install instructions and it did not seem to read from Houdini/cfg/config.yaml so I had to change the following files:
Houdini/config/packages/crayfish_commons.yaml - updated URLs and added syn_config and syn_enabled
Houdini/config/packages/monolog.yaml - changed log path to /var/log/islandora/houdini.log
Houdini/config/services.yaml - changed path to convert

I also found that you need to point Apache to the public directory instead of the src directory like you do for the other Crayfish services.

Is this all the intended way for this to work? If so, I can create a pull request on the manual installation documentation for Crayfish and update that.

Thanks

**Comment by whikloj** [comment]
🤦 Sorry @joshdentremont and @kayakr, I apologize for letting this sit so long. New PR up.

**Comment by kstapelfeldt** [comment]
Closing as it has been resolved with pull request.
