### ISSUE TITLE
Islandora Settings offers invalid time expression

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1498]
On Islandora Settings in Drupal (`/admin/config/islandora/core`) the JWT Expiry field description suggests times like `60, "2 days", "10h", "7d"` but if you try `7d` the form errors with `"7d" is not a valid time or interval expression."` Do the offered times all need "+" added, e.g. `+7d` works.
<img width="572" alt="Screen Shot 2020-05-05 at 11 35 17 AM" src="https://user-images.githubusercontent.com/208184/81023479-a7501900-8ec4-11ea-92de-ffb82ba4522f.png">

**Comment by seth-shaw-unlv** [comment]
Ah, you are right. It validates using [strtotime](https://www.php.net/manual/en/function.strtotime.php). All the examples _should be_ valid [relative forms](https://www.php.net/manual/en/datetime.formats.relative.php) which, for the existing ones, require the "+" sign at the beginning (because using the minus makes no sense in this context). The line to update is [here](https://github.com/Islandora/islandora/blob/8.x-1.x/src/Form/IslandoraSettingsForm.php#L92).

**Comment by whikloj** [comment]
Would this benefit from some help in the validation function? Like assuming/requiring a `+` because a JWT with a `-` is kinda useless.

**Comment by seth-shaw-unlv** [comment]
@whikloj, sure. The validation code currently insists it is a valid time, although we could improve the validation error message.

**Comment by rosiel** [comment]
Still an issue, in a way. '2 days' does not validate because 'day' is not listed as one of the valid time intervals. Yet it's in the suggested text.
![Screen Shot 2021-09-10 at 4 34 05 PM](https://user-images.githubusercontent.com/1943338/132908002-aa85db13-990d-48bb-b71a-13ec17cf3ea6.png)

**Comment by seth-shaw-unlv** [comment]
Thanks, @rosiel for wrapping this up for us!
