### ISSUE TITLE
Update Openseadragon for Drupal 9

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1729]
This is the one remaining module for the Drupal 9 sprint that hasn't been updated yet.  We need to run it through the update checker tools and the Drupal practice sniffer like we have for `islandora`, `islandora_defaults`, and all the other modules.

**Comment by elizoller** [comment]
the biggest issue here i think is the libraries module which is not d9 ready at all. i think that the switch to using CDN may have actually removed our dependency on the libraries module though. but i'd need someone way more familiar with this module to confirm that.

**Comment by dannylamb** [comment]
I _think_ that's still done using libraries.  I'll have to double check.

**Comment by dannylamb** [comment]
Y'know looking at the documentation it's not super clear at all.  There are core libraries and then the libraries API, which purports to be for `external` libraries, but I don't think we're using the same terminology.

I think the "blow it away and see what happens" approach will be best here :fire: :fire: :fire:

**Comment by elizoller** [comment]
yeah i couldn't figure it out from the docs either. i tried to "drush pm-uninstall libraries" on a d9 site but that made it unhappy so i wonder if i'd have needed to not install it all or uninstall when i was still on 8 and then remove before upping to 9. eventually what i did (super hacky) was to just remove all the files in the libraries directory and empty out the module and info so that it was still "there" and "installed" but literally did nothing. and i was still able to get OSD working.... so i probably just did the things in the wrong order

**Comment by dannylamb** [comment]
Resolved via https://github.com/Islandora/openseadragon/commit/1401a03bb689aa7a223e4431efde8af01c0a83d4
