### ISSUE TITLE
hook_post_action is not D9 ready

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1731]
We use this for multi-file media and it looks like it's not going to get updated to D9.  It most likely could be replaced wtih an Event.  Here's what they're doing: https://github.com/Islandora/islandora/blob/8.x-1.x/islandora.module#L172-L183

**Comment by qadan** [comment]
Some commentary on this, just for clarity's sake:

https://www.drupal.org/project/drupal/issues/2551893 - entity events are something that is still being implemented in Drupal 9. I think it would be prudent to wait for this to drop before moving over to the event model. I'm not sure it would make sense for us to roll our own event into this, since currently implementing such an event would just be a roundabout implementation of existing hooks.

I think we should pare down what `hook_post_action` is doing for our own purposes - namely, registering a shutdown function after the entity is saved which fires the reaction. Then we can revisit this once the above issue is resolved and conventions for event handling in entities is solidified.

**Comment by elizoller** [comment]
i think this one can be closed? @qadan @dannylamb
