### ISSUE TITLE
EDTF dates are added twice to jsonld

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1767]
Make a node and give it a value for an EDTF field.  I gave mine a created date of 2020-01-01.

![image](https://user-images.githubusercontent.com/20773151/109163251-81e01480-774f-11eb-8baf-10f8bcf805c5.png)

Go check out the jsonld for the node and the EDTF value is duplicated :confused: 

![image](https://user-images.githubusercontent.com/20773151/109163602-e0a58e00-774f-11eb-9981-49739fb58a33.png)

**Comment by dannylamb** [comment]
Looking at this after @whikloj pointed it out, and it's duplicated because there is both a string an a date representation.  They just happen to be the same.

This could potentially be on purpose.  Maybe @seth-shaw-unlv knows more?

**Comment by seth-shaw-unlv** [comment]
Yes, this was intentional, allowing us to preserve the original string value and provide a Date typed representation.

**Comment by seth-shaw-unlv** [comment]
This was because the EDTF spec didn't have a type URI we could use, nor if it did, would it likely be widely adopted yet by those parsing and querying dates from JSON-LD or the triplestore. However, many EDTF dates do conform (or have "close enough" versions) to these standard date forms and we wanted to make them available.

**Comment by dannylamb** [comment]
Awesome @seth-shaw-unlv , makes sense.  Closing :sweat_smile:
