### ISSUE TITLE
Composer not grabbing latest commits of islandora/islandora:dev-8.x-1.x

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#1866]
## PRs:
1.  https://github.com/Islandora-Devops/islandora-project/pull/1
1. https://github.com/Islandora-Devops/islandora_profile/pull/1

I was having trouble running a migration and it turned out that even though I had run composer update, the latest commit of islandora/islandora was not being downloaded.

On the packagist.org page for islandora/islandora it says:

> This package is auto-updated.
>
> Last update: 2021-06-07 13:50:52 UTC

I don't know why Packagist is  not auto-updating but I think we should declare these repositories explicitly in composer.json.

This confers several advantages, like making it more straight forward for developers to work on their own branche.

**Comment by dannylamb** [comment]
I sent an email out to the contact I could find on packagist.org, and none other than @Seldaek responded and helped me out!  We've got packagist auto-updating now!

I'm fine to leave it on Github in these composer.json files for now since it does help folks who are developing on their own forks and don't want to push to the foundation's repos.  But I think we can encourage folks to use packagist for production and consider this closed.

No more clicking the update button manually on packagist for me!!! :rocket:
