### ISSUE TITLE
Advance Search block should work, by redirecting the user to the page with the view if used on a page where the view is not present

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora/documentation#1869]
This will only work with blocks that are associated with a 'page view' as it needs a page to redirect to.

**Comment by nigelgbanks** [comment]
<img width="998" alt="Screen Shot 2021-07-12 at 12 15 58 PM" src="https://user-images.githubusercontent.com/487373/125342458-db3a9000-e34c-11eb-808f-7b71aaa2b30b.png">
<img width="1073" alt="Screen Shot 2021-07-12 at 12 43 02 PM" src="https://user-images.githubusercontent.com/487373/125342470-df66ad80-e34c-11eb-9423-558f136f692a.png">

**Comment by kylehuynh205** [comment]
I think I encountered this issue, just wondering if the URL gets changed with the query string when the Search button is pressed ? If not, it's either because of the "Use Ajax" under Advanced Tab in the view need to be set to "Yes" and the Facet blocks need to be placed in the page as well. Hope this can help.

**Comment by nigelgbanks** [comment]
Forgot to close this after it was fixed by this [pull](https://github.com/Islandora/islandora/pull/843)
