### ISSUE TITLE
Islandora Defaults testing instructions

### ISSUE THREAD

**Issue by DonRichards** [Islandora/documentation#2062]
Islandora Defaults need documented testing instructions. This process isn't simple and is not the typical Drupal module test. 

Because this isn't consistent with typical Drupal modules testing and isn't specific to just a single PR I feel like these instructions are needed to make "testing" and "reviewing" more approachable.

**Comment by rosiel** [comment]
This was related to Seth's ticket #1977 . I documented what worked for me on that front, here: https://docs.lefaive.ca/w/index.php/Testing_Pull_Requests#Example%3A_Pulling_in_a_PR_branch_for_Islandora_Defaults_with_the_Playbook 

There are some old instructions for testing with isle as well, which need to be tested since the partial move to theinstall profile, but the part is under the Example... playbook.

**Comment by rosiel** [comment]
Islandora Defaults is being deprecated. The testing instructions for its replacement the [Starter Site](https://github.com/Islandora/islandora-starter-site/), are:

* You must create a fresh new site to test the starter site. That's just how it works. You will destroy your old site.
* ISLE: change the line reading `composer create-project islandora/islandora-starter-site:dev-main` to specify the branch (the branch name, here `main` is preceded by `dev-` because it does not look like a version string. if the branch name in question was `2.x` then you would ask for `2.x-dev`. I was today years old when I learned this.). I do not think there is a way to change to a forked repo.
* Playbook: change `drupal_deploy_repo` to the appropriate github repo. Change `drupal_deploy_version` to your branch. Do not add `dev-` or `-dev` to the branch in this case.
