### ISSUE TITLE
Document Milliner configuration for fedora6

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#2074]
Milliner has some special logic when running against a Fedora 6 repository which is [set via a config](https://github.com/Islandora/Crayfish/blob/2.x/Milliner/src/app.php#L32-L39). Unfortunately, this config setting isn't in the README nor is it in the default config, which means you have to read the code to know it exists.

(This made testing an upgrade from Fedora 5 to Fedora 6 for our Islandora site more arduous than it needed to be.)

We should document this.

**Comment by ysuarez** [comment]
@seth-shaw-unlv I have a few initial questions... 

Is this something that only applies when moving from Fedora 5 to Fedora 6 in an existing Islandora 2 instance, or is this only/also for those that want to use Fedora 6 from the beginning?

My PHP skills are rusty, so let me see if I am understanding what has to be documented.

My guess is that the README has to mention that this value has to be set somewhere (in Milliner?)...

` $app['crayfish.fedora6'] `

So that the logic in [this code](https://github.com/Islandora/Crayfish/blob/2.x/Milliner/src/app.php#L32-L39) returns true, i.e. that you are running Fedora 6?

Am I on the right track? 

Thanks.

**Comment by whikloj** [comment]
@ysuarez Yes. You need to alter your configuration to specify 
```
fedora6: true
```
in Milliner's configuration file if you are using Fedora 6.

It might be good to actually add this option (commented out) to the sample configuration file with some explanatory text.

The reason for this is because Fedora 5 had an undocumented representation called "minimal", and in Fedora 6 we removed that and you now need to use the appropriate Prefer headers to get the same output.

So in Fedora 6 you need to specify to [NOT return ServerManagedTriples](https://github.com/Islandora/Crayfish/blob/fd4284bf9b6e46b2a3d5b836baf6c48ef370e490/Milliner/src/Service/MillinerService.php#L195-L198) when GETting the resource.

On the PUT side Fedora 5 would accept a [`received=minimal` pair on the Prefer header](https://github.com/Islandora/Crayfish/blob/fd4284bf9b6e46b2a3d5b836baf6c48ef370e490/Milliner/src/Service/MillinerService.php#L274-L276) which was also a non-standard. In Fedora 6 this is no longer required and just using `handling=lenient` means that ServerManagedTriples (ie. things you can't change anyways) are ignored from the RDF you are sending.

**Comment by whikloj** [comment]
Sorry missed this
> Is this something that only applies when moving from Fedora 5 to Fedora 6 in an existing Islandora 2 instance, or is this only/also for those that want to use Fedora 6 from the beginning?

It is required for **any** institution using Fedora 6.

**Comment by seth-shaw-unlv** [comment]
Thanks for jumping in, @whikloj. I figure we can add the `fcrepo6: true` in the config file, as Jared said, somewhere around here: https://github.com/Islandora/Crayfish/blob/2.x/Milliner/cfg/config.example.yaml#L7. 

We would then just need add a note about needing this value to be true when running against Fedora 6 somewhere in [the README's configuration section](https://github.com/Islandora/Crayfish/blob/2.x/Milliner/README.md?plain=1#L20-L25).

**Comment by ysuarez** [comment]
@seth-shaw-unlv and @whikloj (BTW, hello and hope you are well) 

with these comments I think I can create a draft PR 

* to add a `fcrepo6: true` config entry in the [config.example.yaml](https://github.com/Islandora/Crayfish/blob/2.x/Milliner/cfg/config.example.yaml#L7) file, though it should be cemented out. I can add a comment simply stating that this is required for using Fedora 6, but I can try to give some technical details if we want.

* to add a sentence in the [the README's configuration section](https://github.com/Islandora/Crayfish/blob/2.x/Milliner/README.md?plain=1#L20-L25) stating that the new config value needs to be uncommented and left as true if running Fedora 6

Unless told otherwise I will work on this PR today.
