### ISSUE TITLE
[DOCS] CRAYFISH_DB_xxx in manual installation documentation for Milliner component

### ISSUE THREAD

**Issue by robyj** [Islandora/documentation#2182]
* **If applicable, link to the [documentation page](https://islandora.github.io/documentation/) relevant to your issue below.**
https://islandora.github.io/documentation/installation/manual/installing_crayfish/

* **If this is a request for __new__ documentation, where in the [existing documentation](https://islandora.github.io/documentation/) does this documentation belong?**

* **Describe your documentation request.**
*The documentation for configuration of the Milliner component makes use of CRAYFISH_DB_xxx (USER/DB/PASSWORD which seems to be part of the gemini component that is no longer used. I cannot continue my manual installation any further due to this bug

* **Which version of islandora are you using?**
* 2.0

* **What user roles is this documentation intended for?**

Administrator

* **What implementations of islandora does this documentation request apply to?**
2.0

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by rosiel** [comment]
Oof, that's not a good look. Sorry you ran into that. 

I know this is not helpful, but I have an [open PR that adds a warning disclaimer](https://github.com/Islandora/documentation/pull/2176) to all the manual install instructions. We know they're broken, and so thank you for pointing out where.

What might be more useful is the [ansible role that installs Crayfish](https://github.com/Islandora-Devops/islandora-playbook/tree/dev/roles/internal/Islandora-Devops.crayfish) (part of the Playbook). I have never done a manual install but, in theory at least, the ansible role should go through the same steps that a manual installation would. Some things might be different (locations, versions, etc).

**Comment by ysuarez** [comment]
@robyj I just wanted to give you a non-update to your issue. We now have now added a warning at the top of that page so that people are not trying to use these out of date manual installation docs...


"...
Needs Maintenance

The manual installation documentation is in need of attention. We are aware that some components no longer work as documented here. If you are interested in helping us improve the documentation, please see Contributing.
..."

<img width="799" alt="image" src="https://user-images.githubusercontent.com/725449/200925470-7ca4e0dd-6b99-4262-811d-82aec7ad668e.png">

**Comment by ysuarez** [comment]
Should we close this issue?

**Comment by robyj** [comment]
Hi

I ended up asked jared whiklo about this issue and he said that those values aren't even being used and to ignore them. I continued and it seems to have worked.

I think you can close this issue. thanks for checking

Jon

**Comment by ysuarez** [comment]
Glad to hear it.
