### ISSUE TITLE
[DOCS] Improve "Install a demo" from Islandora Camp 2023 feedback

### ISSUE THREAD

**Issue by ysuarez** [Islandora/documentation#2218]
* **If applicable, link to the [documentation page](https://islandora.github.io/documentation/) relevant to your issue below.**

https://islandora.github.io/documentation/installation/install-a-demo/

* **If this is a request for __new__ documentation, where in the [existing documentation](https://islandora.github.io/documentation/) does this documentation belong?**

* **Describe your documentation request.**

During the Islandora Camp 2023 we had some feedback on the "Install a demo" documentation. I want to use this issue to collect all of that feedback.

Here we can create a list of doc issues we want to address from the camp:

1. document how to shut down the demo
2. ??? 

* **Which version of islandora are you using?**

Islandora 2

* **What user roles is this documentation intended for?**

All users

* **What implementations of islandora does this documentation request apply to?**

ISLE2 + starter site

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by ysuarez** [comment]
@kstapelfeldt please drop in issues here from your camp notes.

**Comment by kstapelfeldt** [comment]
we had networking issues, people didn't have sufficient space, it was difficult to find where "stacks" were, and people didn't know how long they should wait. Sometimes containers would start and stop, and people would restart them, leading to some content not being ingested. Sometimes the content was created, but the view wasn't, so that led to people reingesting the content repeatedly. Some people triggered workbench directly from within the container to get content ingested. Rebecca is going through the recordings over the next while and will add anything additional. It would be good to get a "troubleshooting" section into the documentation.

**Comment by ysuarez** [comment]
Update from @rebeccapower, there is no video recording of the participants troubleshooting issues. Rebecca will work on tracking down any Zoom chat messages from those days to see if we can gleam details of issues and solutions.

**Comment by rebeccapower** [comment]
I have created an instructional video on how to install Docker Desktop on Windows 10 and get Starter Site running, and am working on creating the Mac OS counterpart. The timeline right now is to have all of that posted online by the end of next week (May 12). Additionally, I will be adding more troubleshooting solutions and workarounds to the [Install A Demo](https://islandora.github.io/documentation/installation/install-a-demo/) page within the next few days/early next week.

**Comment by rebeccapower** [comment]
I have added a Troubleshooting section to the Install a Demo page with what arose from Camp and my own personal installation experience.

**Comment by rebeccapower** [comment]
A How to Install Docker Desktop and Set Up Starter Site video has been created and uploaded to Youtube: https://youtu.be/xhJft9K-YMU

**Comment by rosiel** [comment]
Done, mostly with this [commit](https://github.com/Islandora/documentation/commit/efe828e3afde3a5d31b30778dc80b76724f7eb37).
