### ISSUE TITLE
JSONLD Framing

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#503]
Based on the conversation in #491, we need to have a larger discussion of how to best implement framing.

At this point, I see it to be similar to #493, where we'd need to generate a frame per bundle, based on the bundle's fields and rdf mapping.   As mentioned in the conversation, we'd still have to figure out how to resolve occurrences of multiple frames matching a single bundle.

**Comment by ajs6f** [comment]
There is another point to be considered-- if bundles can overlap (contain the same properties) then frames determined on a per-bundle basis could overlap (discuss the same properties) and possibly disagree and there will have to be either a deterministic way to resolve disputes (if the bundle registry is ordered, maybe first bundle wins?) or an acknowledgement that configs with overlapping frames are broken by user error and will produce weirdness around resources using overlapping bundles/types.

**Comment by DiegoPino** [comment]
@ajs6f I would say context (not `@context` is everything) in the case of overlapping (bundles and in consequence frames) the questions important issue to solve is resource creation (even if that never happens on this part of the code) only creates a single resource.

let me explain myself with a simple pseudo-chained actions list

1. JSON-LD is passed to "Drupal Content type" or "BundleResolver" solver API endpoint.
2. API does magic, processes de JSON-LD, applies framing, matches, discerns, cleans, decides on output, etc and "decides" that JSON-LD matches 2 different Bundles. Since matching/on framing/ algorithm can be non-binary (means some algorithms could even come with partial % matching) depending on what we code, this matching should be an extra qualifier in the response also
3. It returns ALL matched bundles and the qualifiers.
4. The calling class, algorithm or client is who decides what to do. Here is when "Context" of Who is and Why is it calling the endpoint and how it is going to use that data comes in place. I feel the bundleSolver should not make discerning/discarding operations.  The Caller, or in the case of the simplest use case, the operation that is finally going to "create a single, new resource" based on the JSON-LD passed should decide (even if it is as simple as taking the first element) which bundle to use.

Why? because many future needs could be attached to the bundle solving needs, and even those algorithms, framing, etc can be made more efficient or better, but the true is that we can't say for sure we will have always just one need, single context of use, one way of calling an using this service (and framing). While I write this I can already imagine some use cases, like a way of passing a "frame" like JSON-LD to the bundleResolver API to get, build in such a way, that it could respond with all bundles that are able to describe "images or pictures" for example. That could be something you could end needing!

**Comment by dannylamb** [comment]
@DiegoPino This is precisely why the bundle resolver is encapsulated as a service, so that different implementations can be provided as needs arise/change.

> JSON-LD is passed to "Drupal Content type" or "BundleResolver" solver API endpoint.

Although, from the sounds of it, you're envisioning this as a separate web service instead of just a Drupal service?  Or are you talking about POSTing to a create a resource?

Also, if frames are not 1:1 with bundles, then perhaps they are a poor choice for determining bundle?  If anything, I'd try and associate the appropriate frames per bundle and then do a basic db lookup to find/apply what I need.

**Comment by kstapelfeldt** [comment]
We are lost, and this is quite old. Please feel free to resubmit or re-open with additional details (a use case would be great).
