### ISSUE TITLE
Adding 'Preservation Master' tag to media after Ingestion

### ISSUE THREAD

**Issue by jonathangreen** [Islandora/documentation#851]
If you forget to tag media as a preservation master when initially adding it, then modify the media to add the tag, then CLAW does not pickup the change and create derivatives.

Test case:
1. Create new `Repository Item` with tag `image`
2. Add a media to your new `Repository Item` with no tag
3. No derivatives as you would expect
4. Update the media to add the tag `Preservation Master`
5. Save media
6. Still no derivatives created

**Comment by seth-shaw-unlv** [comment]
To manually correct, after adding the Preservation Master tag: select the repository item in question on the Content page and then use the 'generate service file' action. This will fire off both the service file and will also trigger the thumbnail creation.

**Comment by jonathangreen** [comment]
I agree you can manually correct, but shouldn't we be triggering when changes are made to the object?

**Comment by seth-shaw-unlv** [comment]
@jonathangreen, I agree, it would make sense to trigger derivatives in some cases. I just wanted to be sure people knew it was possible in the mean-time when the look into the issue.

**Comment by dannylamb** [comment]
@jonathangreen Currently, if you add the preservation master tag after the fact, the RDF for it should wind up in Fedora.  But since bits didn't change in the binary, it doesn't trigger derivatives.  It tries to be smart about it to prevent unneccessary computations, but I'm sure we can rig it up as long as we can isolate the event of the term being added.

**Comment by jonathangreen** [comment]
This one came in as some folks at Islandora Camp were testing out CLAW and forgot the tag. It seemed like a reasonable use case to me when they expected it to work once correcting the tag.

**Comment by manez** [comment]
I tripped over exactly this same thing when setting up CLAW content for iCampHRM. Definitely jarring for a front-end user 👍

**Comment by rosiel** [comment]
Another couple "did things in the wrong order" use cases, seemingly related. 

1. If you create a media object not attached to an object (perhaps because the Media Of thing wasn't filled out), then link it up later, derivatives won't get generated. Even if you tagged everything right  [note: since this ticket was created, we stopped using "Preservation Master" as the source of derivatives and now we use "Original File"] 

2. If you tag the node as an Audio (or something other than Image) and then add your media, and switch the node to Image, then you don't get derivatives.

In both cases, you can fix it on the "Content" page as @seth-shaw-unlv  pointed out.
